os: linux
dist: focal # needed to use python 3.7
language: python

python:
  - 3.7

addons:
  ssh_known_hosts:
    - 173.255.232.131

branches:
  only:
    - master

install:
  - pip3 install -r requirements.txt

script:
  - sphinx-build -b html docs docs/_build/html

after_success:
  - scripts/deploy.sh
