os: linux
dist: focal # needed to use python 3.7
language: python

python:
  - 3.7

addons:
  ssh_known_hosts:
    - 173.255.232.131

install:
  - pip3 install -r requirements.txt

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script: sphinx-build -b html docs docs/_build/html
    - stage: deploy
      script: bash scripts/deploy.sh
