site_name: Koinos Documentation
site_url: https://docs.koinos.io

site_description: Documentation for Koinos

repo_name: koinos
repo_url: https://github.com/koinos/koinos

edit_uri: https://github.com/koinos/koinos-docs/master/docs/

copyright: Copyright 2023-2024 Koinos Group

docs_dir: docs

theme:
  name: material
  language: en
  icon:
    edit: material/pencil
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  favicon: assets/koinos-icon-dark.png
  logo: assets/koinos-mark-light.svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/koinos
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/koinos/
    - icon: fontawesome/brands/discord
      link: https://discord.koinos.io
    - icon: fontawesome/brands/telegram
      link: https://t.me/koinos_community
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheKoinosGroup
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@koinosgroup

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

nav:
  - Overview:
    - overview/index.md
    - overview/blockchain-basics.md
    - overview/mana.md
    - overview/proof-of-burn.md
    - overview/tokenomics.md
    - overview/smart-contracts.md
    - overview/governance.md
  - Developers:
    - developers/index.md
    - developers/as-sdk.md
  - Validators:
    - validators/index.md
  - Architecture:
    - architecture/index.md
  - Resources:
    - resources/index.md
